### PR TITLE
util.zeros() returns undefined

### PR DESCRIPTION
**Pull request by asinyagin**
Hey,

Fix of the error because of which `npm test` fails with the message:
```
  1) zeros function should produce lots of 0s:
     TypeError: Cannot call method 'toString' of undefined
      at Context.<anonymous> (test/index.js:9:22)

  2) pad should pad a Buffer:
     TypeError: Cannot read property 'length' of undefined
      at Buffer.copy (buffer.js:517:13)
      at Object.exports.pad (index.js:43:9)
      at Context.<anonymous> (test/index.js:33:27)
```

### CODE REVIEW

**Comment by asinyagin** [comment]
This errors leads to the error in runCode() of ethereumjs-lib 0.5.0:
```
buffer.js:517
      target.length === 0 ||
            ^
TypeError: Cannot read property 'length' of undefined
    at Buffer.copy (buffer.js:517:13)
    at Object.exports.pad (/home/alexander/Documents/ethergit/ethereumjs-test/node_modules/ethereumjs-lib/node_modules/ethereumjs-util/index.js:43:9)
    at opFuncs.MSTORE (/home/alexander/Documents/ethergit/ethereumjs-test/node_modules/ethereumjs-lib/lib/vm/runCode.js:669:24)
    at /home/alexander/Documents/ethergit/ethereumjs-test/node_modules/ethereumjs-lib/lib/vm/runCode.js:984:17
    at /home/alexander/Documents/ethergit/ethereumjs-test/node_modules/async/lib/async.js:735:13
    at iterate (/home/alexander/Documents/ethergit/ethereumjs-test/node_modules/async/lib/async.js:253:13)
    at process._tickCallback (node.js:448:13)
```

**Comment by wanderer** [comment]
@asinyagin are you using node version 0.10.x ?

**Comment by wanderer** [comment]
ok i see from you other comment on ethereumjs-lib that you are. You need to be using 11 or above. I'm a bit hesitate to try to support 10 right now b/c other  things will also break. Can you upgrade to 11 or above?

**Comment by wanderer** [comment]
@asinyagin thanks!

**Pull request merged**
